export const strings = {
  bn: {
    appName: 'BondCheck BD',
    home: 'হোম',
    myBonds: 'আমার বন্ড',
    scan: 'স্ক্যান',
    results: 'ফলাফল',
    settings: 'সেটিংস',
    addBond: 'বন্ড যোগ করুন',
    scanBond: 'বন্ড স্ক্যান করুন',
    youWon: '🎉 আপনি জিতেছেন!',
    noPrize: 'এই ড্রতে কোনো পুরস্কার নেই',
    bondNumber: 'বন্ড নম্বর',
    latestDraw: 'সর্বশেষ ড্র',
    myWins: 'আমার পুরস্কার',
    noWinsYet: 'এখনো কোনো পুরস্কার নেই',
    loading: 'লোড হচ্ছে...',
    login: 'লগইন',
    register: 'নিবন্ধন',
    logout: 'লগআউট',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    name: 'নাম',
    send: 'পাঠান',
    verify: 'যাচাই করুন',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    confirm: 'নিশ্চিত করুন',
    totalBonds: 'মোট বন্ড',
    totalWins: 'মোট জয়',
    // New keys
    greeting: 'স্বাগতম',
    nextDraw: 'পরবর্তী ড্র',
    daysLeft: 'দিন বাকি',
    today: 'আজ',
    tomorrow: 'আগামীকাল',
    totalValue: 'মোট মূল্য',
    searchBonds: 'বন্ড নম্বর বা সিরিজ দিয়ে খুঁজুন',
    noBondsYet: 'এখনো কোনো বন্ড যোগ করা হয়নি।',
    bondValueNote: 'প্রতিটি বন্ড = ৳১০০',
    afterTax: 'করের পরে',
    daysToExpiry: 'দিনে মেয়াদ শেষ',
    expiringSoon: '⚠️ মেয়াদ শেষ হচ্ছে',
    shareWin: 'জয় শেয়ার করুন',
    shareApp: 'অ্যাপ শেয়ার করুন',
    rateApp: 'অ্যাপ রেটিং দিন',
    privacyPolicy: 'গোপনীয়তা নীতি',
    contactUs: 'যোগাযোগ করুন',
    version: 'সংস্করণ',
    about: 'সম্পর্কে',
    dataSource: 'তথ্যসূত্র',
    winsNoWins: 'এখনো কোনো পুরস্কার নেই — বন্ড যোগ করুন, আমরা স্বয়ংক্রিয়ভাবে চেক করব।',
    seeAll: 'সব দেখুন',
    drawCountdownNote: 'বাংলাদেশ পুরস্কার বন্ড ড্র',
    copyNumber: 'নম্বর কপি হয়েছে',
    inviteFriends: 'বন্ধুদের আমন্ত্রণ জানান',
    referralDesc: 'আপনার কোড শেয়ার করুন। প্রতি রেফারেলে ৫টি অতিরিক্ত বন্ড স্লট পান!',
    referrals: 'রেফারেল',
    bonusSlots: 'বোনাস স্লট',
    copyCode: 'কপি',
    shareReferral: 'রেফারেল লিঙ্ক শেয়ার করুন',
    referralCodeCopied: 'রেফারেল কোড কপি হয়েছে!',
    referralShareMsg: 'BondCheck BD দিয়ে আপনার প্রাইজবন্ড ফলাফল তাৎক্ষণিকভাবে দেখুন! বন্ড যোগ করুন আর জিতলে নোটিফিকেশন পান।',
    referralShareCode: 'আমার রেফারেল কোড:',
  },
  en: {
    appName: 'BondCheck BD',
    home: 'Home',
    myBonds: 'My Bonds',
    scan: 'Scan',
    results: 'Results',
    settings: 'Settings',
    addBond: 'Add Bond',
    scanBond: 'Scan Bond',
    youWon: '🎉 You Won!',
    noPrize: 'No prize in this draw',
    bondNumber: 'Bond Number',
    latestDraw: 'Latest Draw',
    myWins: 'My Wins',
    noWinsYet: 'No wins yet',
    loading: 'Loading...',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    send: 'Send',
    verify: 'Verify',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    totalBonds: 'Total Bonds',
    totalWins: 'Total Wins',
    // New keys
    greeting: 'Welcome',
    nextDraw: 'Next Draw',
    daysLeft: 'days left',
    today: 'Today',
    tomorrow: 'Tomorrow',
    totalValue: 'Total Value',
    searchBonds: 'Search by number or series',
    noBondsYet: 'No bonds added yet.',
    bondValueNote: 'Each bond = ৳100',
    afterTax: 'After 20% tax',
    daysToExpiry: 'days to expiry',
    expiringSoon: '⚠️ Expiring soon',
    shareWin: 'Share Win',
    shareApp: 'Share App',
    rateApp: 'Rate App',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    version: 'Version',
    about: 'About',
    dataSource: 'Data Source',
    winsNoWins: 'No wins yet — add your bonds and we\'ll check automatically.',
    seeAll: 'See All',
    drawCountdownNote: 'Bangladesh Prize Bond Draw',
    copyNumber: 'Number copied',
    inviteFriends: 'Invite Friends',
    referralDesc: 'Share your code. Get 5 extra bond slots per referral!',
    referrals: 'referrals',
    bonusSlots: 'bonus slots',
    copyCode: 'Copy',
    shareReferral: 'Share Referral Link',
    referralCodeCopied: 'Referral code copied!',
    referralShareMsg: 'Check your Bangladesh prize bond results instantly with BondCheck BD! Add your bonds and get notified when you win.',
    referralShareCode: 'My referral code:',
  },
} as const;

export type Lang = keyof typeof strings;
