export const strings = {
  bn: {
    appName: 'BondCheck BD',
    home: 'হোম',
    myBonds: 'আমার বন্ড',
    scan: 'স্ক্যান',
    results: 'ফলাফল',
    settings: 'সেটিংস',
    addBond: 'বন্ড যোগ করুন',
    scanBond: 'বন্ড স্ক্যান করুন',
    youWon: '🎉 আপনি জিতেছেন!',
    noPrize: 'এই ড্রতে কোনো পুরস্কার নেই',
    bondNumber: 'বন্ড নম্বর',
    latestDraw: 'সর্বশেষ ড্র',
    myWins: 'আমার পুরস্কার',
    noWinsYet: 'এখনো কোনো পুরস্কার নেই',
    loading: 'লোড হচ্ছে...',
    login: 'লগইন',
    register: 'নিবন্ধন',
    logout: 'লগআউট',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    name: 'নাম',
    send: 'পাঠান',
    verify: 'যাচাই করুন',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    confirm: 'নিশ্চিত করুন',
    totalBonds: 'মোট বন্ড',
    totalWins: 'মোট জয়',
  },
  en: {
    appName: 'BondCheck BD',
    home: 'Home',
    myBonds: 'My Bonds',
    scan: 'Scan',
    results: 'Results',
    settings: 'Settings',
    addBond: 'Add Bond',
    scanBond: 'Scan Bond',
    youWon: '🎉 You Won!',
    noPrize: 'No prize in this draw',
    bondNumber: 'Bond Number',
    latestDraw: 'Latest Draw',
    myWins: 'My Wins',
    noWinsYet: 'No wins yet',
    loading: 'Loading...',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    send: 'Send',
    verify: 'Verify',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    totalBonds: 'Total Bonds',
    totalWins: 'Total Wins',
  },
} as const;

export type Lang = keyof typeof strings;
